sh delly.sh ADB_Blood ADB_LL
sh delly.sh ADB_Blood ADB_LM
sh delly.sh ADB_Blood ADB_UL
sh delly.sh ADB_Blood ADB_UM
sh delly.sh LMS_Blood LMS_Cancer
sh delly.sh LMS_Blood LMS_LN_3L1
sh delly.sh LMS_Blood LMS_LN_3R1
sh delly.sh LMS_Blood LMS_Recur
sh delly.sh SJH_Blood SJH_Cen1
sh delly.sh SJH_Blood SJH_Isth
sh delly.sh SJH_Blood SJH_Lat 
sh delly.sh SJH_Blood SJH_LN
