sh varscan.sh ADB_Blood ADB_LL
sh varscan.sh ADB_Blood ADB_LM
sh varscan.sh ADB_Blood ADB_UM
sh varscan.sh ADB_Blood ADB_UL
sh varscan.sh LMS_Blood LMS_Cancer
sh varscan.sh LMS_Blood LMS_LN_3R1
sh varscan.sh LMS_Blood LMS_LN_3L1
sh varscan.sh LMS_Blood LMS_Recur
sh varscan.sh SJH_Blood SJH_Cen1
sh varscan.sh SJH_Blood SJH_Isth
sh varscan.sh SJH_Blood SJH_Lat
sh varscan.sh SJH_Blood SJH_LN
